version: '3'
services: 
  node-app:
    image: ghcr.io/alekseysuev/rest-key-value:invicara-test-app
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    network_mode: host
    depends_on: 
      - redis
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"