sudo: required
services:
  - docker

before_install:
  - docker build -t alekseysuev/projects/docker-react/frontend -f dockerfile.dev .


script:
  - docker run alekseysuev/projects/docker-react/frontend npm install test -- --coverage
